[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.54.0",
    "beautifulsoup4>=4.13.4",
    "openai>=1.88.0",
    "requests>=2.32.4",
    "trafilatura>=2.0.0",
]
